### ISSUE TITLE
Unable to find firebase service account credentials file Github Actions. 

### ISSUE THREAD

**Issue by aliumujib** [wzieba/Firebase-Distribution-Github-Action#52]
Hi, I'm try to setup firebase app distribution on Github actions for my project. I am currently stuck with an issue where the credentials file is not found no matter where I store it.

My work flow is as follows:
- Build Debug app
- Fetch credentials file (Decode the Base64 string and write it to a file in `~/Firebase-Distribution-Github-Action/` directory)
- Upload .apk artifact to firebase app distribution

My workflow file is as follows:

```
name: Test and Deploy

on:

  push:
  pull_request:
  workflow_dispatch:

jobs:

  unit-tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Unit Tests
        run: ./gradlew test --warning-mode=all

  deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build Debug App
        run: ./gradlew assembleDebug --warning-mode=all

      - name: Fetch credential file
        uses: ./.github/actions/base64-to-file
        with:
          secret: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          filename: credential_file.json
          destination-path: ~/Firebase-Distribution-Github-Action/

      - name: Upload Artifact To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFile: /home/runner/Firebase-Distribution-Github-Action/credential_file.json
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true

```

The base64-to-file action can be found [here](https://github.com/davidSchuppa/base64Secret-toFile-action/blob/main/action.yml). I've slightly modified it though, to ensure that the `credential_file.json` is actually created as you will see in this screenshot.

<img width="811" alt="Screenshot 2021-11-05 at 13 36 29" src="https://user-images.githubusercontent.com/13552664/140518924-e3c8763f-97ea-440b-b1b4-5729fea61407.png">

This is the error I get from firebase CLI:

```
Run wzieba/Firebase-Distribution-Github-Action@v1
  with:
    appId: ***
    serviceCredentialsFile: /home/runner/Firebase-Distribution-Github-Action/credential_file.json
    file: app/build/outputs/apk/debug/app-debug.apk
    debug: true
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.13-8/x64
/usr/bin/docker run --name e284905e2b498ba8da4b0889464117d57950f4_0f9cf3 --label e28490 --workdir /github/workspace --rm -e JAVA_HOME -e INPUT_APPID -e INPUT_SERVICECREDENTIALSFILE -e INPUT_FILE -e INPUT_DEBUG -e INPUT_TOKEN -e INPUT_GROUPS -e INPUT_RELEASENOTES -e INPUT_RELEASENOTESFILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=tr...
[2021-11-05T13:45:57.754Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2021-11-05T13:45:57.758Z] Error: The file at /home/runner/Firebase-Distribution-Github-Action/credential_file.json does not exist, or it is not a file. ENOENT: no such file or directory, lstat '/home/runner'
    at Object.realpathSync (fs.js:1651:7)
    at GoogleAuth._getApplicationCredentialsFromFilePath (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:246:27)
    at GoogleAuth._tryGetApplicationCredentialsFromEnvironmentVariable (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:189:25)
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:125:33)
    at GoogleAuth.getClient (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:504:28)
    at GoogleAuth.getAccessToken (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:526:35)
    at autoAuth (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/requireAuth.js:24:32)
    at Object.requireAuth [as fn] (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/requireAuth.js:45:26)
    at /usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/command.js:188:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: Failed to authenticate, have you run firebase login?
[2021-11-05T13:45:57.975Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[2021-11-05T13:45:57.975Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}

```

**Comment by mateuszkwiecinski** [comment]
I'm not familiar with Docker, but I can share my _guess_ what can be the reason 👀 
So, looking at action's config it adds current working directory to docker image https://github.com/wzieba/Firebase-Distribution-Github-Action/blob/2f5f41c98ec11ae01b6a56a405fd03a38a29bd55/Dockerfile#L4 which means only files within the directory will be available when firebase cli gets invoked. 
According to https://docs.github.com/en/actions/learn-github-actions/environment-variables I can interpred  current directory (`.`) as a `GITHUB_WORKSPACE` which means in your case that'd be something like: `/home/runner/work/your-repo-name/your-repo-name`. 
Looking at your config you save the config file outside of `GITHUB_WORKSPACE` `(~/Firebase-Distribution-Github-Action)` which means it won't be present within docker image 

@aliumujib Can you try saving your service file under `GITHUB_WORKSPACE`:
```
      - name: Fetch credential file
        uses: ./.github/actions/base64-to-file
        with:
          secret: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          filename: credential_file.json
          destination-path: ${{ GITHUB_WORKSPACE }}/Firebase-Distribution-Github-Action/
  
    - name: Upload Artifact To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFile: ${{ GITHUB_WORKSPACE }}/Firebase-Distribution-Github-Action/credential_file.json
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true
```
and see if that helps? (I might have mixed something with the config above, so feel free to play with the configuration to somehow place credentials file within _"current directory"_) 
If I'm right that means that's a bug and `serviceCredentialsFile` input should also be added to docker image 👀

**Comment by aliumujib** [comment]
Hey @mateuszkwiecinski, you were right! Thank so much.

I got my config to finally work correctly with the following:

```
      - name: Fetch credential file
        uses: ./.github/actions/base64-to-file
        with:
          secret: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          filename: credential_file.json
          destination-path: $GITHUB_WORKSPACE/Firebase-Distribution-Github-Action/

      - name: Upload Artifact To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFile: Firebase-Distribution-Github-Action/credential_file.json
          file: app/build/outputs/apk/betaDebug/app-betaDebug.apk
          debug: true
```

Once again, thank you for your answer!

**Comment by mateuszkwiecinski** [comment]
@aliumujib Thanks for confirming! I'm glad it worked for you 😄 
I created separate issue to track the issue you encountered originaly: https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/53
